const { _electron } = require('playwright-core');
const { spawn } = require('child_process');
const SP = process.argv[2], root = require('path').resolve(__dirname, '../..');
const env = { ...process.env, PATH: `${SP}/fakebin:${process.env.PATH}`, XDG_CONFIG_HOME: SP + '/e2e-home', BLAZMA_LLAMA_SERVER: SP + '/llama.cpp/build/bin/llama-server', BLAZMA_HF_ENDPOINT: 'http://127.0.0.1:18999' };
const cards = (win) => win.evaluate(() => [...document.querySelectorAll('.stat')].filter((c) => /حرارة المعالج|طاقة المعالج/.test(c.textContent)).map((c) => c.innerText.replace(/\s+/g, ' ')));
(async () => {
  let mock = spawn('node', [SP + '/mock-lhm.js', 'ok'], { stdio: 'inherit' });
  await new Promise((r) => setTimeout(r, 500));
  const app = await _electron.launch({ executablePath: root + '/node_modules/electron/dist/electron', args: [root, '--no-sandbox'], cwd: root, env });
  const win = await app.firstWindow(); await win.waitForLoadState('load');
  const logs = []; win.on('pageerror', (e) => logs.push('pageerror: ' + e.message)); win.on('console', (m) => m.type() === 'error' && logs.push('console: ' + m.text().slice(0, 200)));
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1366, 900));
  await win.waitForTimeout(1500);
  await win.click('.nav-item[data-page="device"]'); await win.waitForTimeout(5000);
  console.log('with LHM:', await cards(win));
  await win.locator('.stat:has-text("حرارة المعالج")').scrollIntoViewIfNeeded(); await win.mouse.move(5, 5);
  await win.screenshot({ path: SP + '/lhm-1.png' });
  mock.kill(); await new Promise((r) => setTimeout(r, 300));
  mock = spawn('node', [SP + '/mock-lhm.js', 'auth'], { stdio: 'inherit' });
  await win.waitForTimeout(13000);
  console.log('auth:', await cards(win));
  mock.kill(); await win.waitForTimeout(13000);
  console.log('off:', await cards(win));
  await win.evaluate(() => window.blazma.updateSettings({ lhmEnabled: false })); await win.waitForTimeout(3000);
  console.log('disabled:', await cards(win));
  await win.evaluate(() => window.blazma.updateSettings({ lhmEnabled: true }));
  console.log(logs.join('\n') || 'no errors');
  await app.close();
})().catch((e) => { console.error('FAIL', e); process.exit(1); });
