const { _electron } = require('playwright-core');
const SP = process.argv[2], root = require('path').resolve(__dirname, '../..');
const env = { ...process.env, PATH: `${SP}/fakebin:${process.env.PATH}`, XDG_CONFIG_HOME: SP + '/e2e-home', BLAZMA_LLAMA_SERVER: SP + '/llama.cpp/build/bin/llama-server', BLAZMA_HF_ENDPOINT: 'http://127.0.0.1:18999' };
const termText = (win) => win.locator('.term-row').allInnerTexts();
(async () => {
  const app = await _electron.launch({ executablePath: root + '/node_modules/electron/dist/electron', args: [root, '--no-sandbox'], cwd: root, env });
  const win = await app.firstWindow(); await win.waitForLoadState('load');
  const logs = []; win.on('pageerror', (e) => logs.push('pageerror: ' + e.message)); win.on('console', (m) => m.type() === 'error' && logs.push('console: ' + m.text().slice(0, 300)));
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1366, 860));
  await win.waitForTimeout(1500);
  await win.click('.nav-item[data-page="studio"]'); await win.waitForTimeout(2500);
  await win.keyboard.press('F1'); await win.waitForTimeout(400);
  await win.keyboard.type('مشروع جديد'); await win.waitForTimeout(300); await win.keyboard.press('Enter'); await win.waitForTimeout(600);
  console.log('palette:', await win.locator('.pal-list .pal-label').allInnerTexts());
  await win.click('.pal-list .pal-label:text-is("بايثون")'); await win.waitForTimeout(1500);
  const t0 = Date.now();
  await win.keyboard.press('F5');
  await win.waitForFunction(() => [...document.querySelectorAll('.term-row')].some((r) => r.textContent.includes('المجموع')), null, { timeout: 60000 });
  console.log('first run ms:', Date.now() - t0);
  console.log('lang:', await win.textContent('.wb-status').then((t) => /Python/.test(t)));
  const cmd = async (c, wait = 4000) => {
    const before = (await termText(win)).length;
    await win.fill('.term-input', c); await win.press('.term-input', 'Enter');
    await win.waitForTimeout(wait);
    const rows = await termText(win);
    console.log(`$ ${c}\n   ` + rows.slice(before + 1).join('\n   '));
  };
  console.log('run output:\n   ' + (await termText(win)).slice(-6).join('\n   '));
  const t1 = Date.now(); await cmd('python -c "print(sum(range(10)))"', 1500); console.log('second run ms ~', Date.now() - t1);
  await cmd('python -c "1/0"');
  await cmd('echo "def f(): return 42" > helper.py', 500);
  await cmd('python -c "import helper; print(helper.f())"');
  await cmd('python -c "open(\'data.txt\', \'w\', encoding=\'utf-8\').write(\'مرحبا\')"');
  await cmd('cat data.txt', 500);
  await cmd('python -c "x = input()"');
  await cmd('pip install numpy', 500);
  await cmd('python -c "import urllib.request; urllib.request.urlopen(\'http://example.com\')"', 5000);
  await win.screenshot({ path: SP + '/py-1.png' });
  await cmd('python -c "while True: pass"', 64000);
  await cmd('python -c "print(\'after timeout\')"', 8000);
  console.log(logs.join('\n') || 'no errors');
  await app.close();
})().catch((e) => { console.error('FAIL', e); process.exit(1); });
